tabWidth: 4
printWidth: 100

plugins:
  - prettier-plugin-svelte
  - prettier-plugin-organize-imports

overrides:
  - files: "*.{yml,yaml}"
    options:
      tabWidth: 2
  - files: "*.svelte"
    options:
      parser: svelte
